import React from 'react';
import './Dashboard.css';

const Dashboard: React.FC = () => {
  return (
    <div className="dashboard-container">
      {/* Top Metrics Row */}
      <div className="metrics-row">
        <div className="metric-card panel">
          <div className="metric-header">
            <span className="band-title">BAND 01 // NATIONAL SNAPSHOT</span>
          </div>
          <div className="metric-content">
            <div className="metric-label">SPR REMAINING</div>
            <div className="metric-value text-main">9.3 <span className="metric-unit">DAYS</span></div>
            <div className="metric-bar-container">
              <div className="metric-bar bg-red" style={{ width: '40%' }}></div>
              <div className="metric-bar-bg"></div>
            </div>
            <div className="metric-footer text-red">CRITICAL THRESHOLD: &lt; 10.0</div>
          </div>
        </div>

        <div className="metric-card panel">
          <div className="metric-content">
            <div className="metric-label">IMPORT DEPENDENCY</div>
            <div className="metric-value text-main">88 <span className="metric-unit">%</span></div>
            <div className="metric-bar-container">
              <div className="metric-bar bg-amber" style={{ width: '88%' }}></div>
              <div className="metric-bar-bg"></div>
            </div>
            <div className="metric-footer text-muted">NET FLOW: -1.2M BPD</div>
          </div>
        </div>

        <div className="metric-card panel">
          <div className="metric-content">
            <div className="metric-label">HIGHEST RISK CORRIDOR</div>
            <div className="metric-value text-red">HORMUZ</div>
            <div className="metric-sub-value text-main">LEVEL: SEVERE</div>
            <div className="risk-blocks">
              <div className="risk-block active bg-red"></div>
              <div className="risk-block active bg-red"></div>
              <div className="risk-block active bg-red"></div>
              <div className="risk-block active bg-red"></div>
              <div className="risk-block bg-dark"></div>
            </div>
          </div>
        </div>

        <div className="metric-card panel">
          <div className="metric-content">
            <div className="metric-label">ALTERNATIVE CAPACITY</div>
            <div className="metric-value text-main">34 <span className="metric-unit">%</span></div>
            <div className="metric-bar-container">
              <div className="metric-bar bg-teal" style={{ width: '34%' }}></div>
              <div className="metric-bar-bg"></div>
            </div>
            <div className="metric-footer text-muted">STANDBY FLOW READY</div>
          </div>
        </div>
      </div>

      {/* Middle Tab Row */}
      <div className="middle-actions">
        <div className="tab-group">
          <div className="tab active">WIRE FEED</div>
        </div>
        <button className="btn-amber">EXTRACT SIGNAL</button>
      </div>

      {/* Bottom Report Panel */}
      <div className="report-panel">
        <div className="band-title">BAND 03 // ANALYTIC ASSESSMENT</div>
        
        <div className="report-box panel">
          <div className="report-header">
            <h3>STRATEGIC VULNERABILITY REPORT</h3>
            <div className="secure-badge">
              <span className="icon">✓</span> SYSTEM SECURE
            </div>
          </div>
          <div className="report-meta">GENERATED BY ENGINE-KAPPA-09 // LATENCY 14MS</div>
          
          <div className="report-body">
            <div className="report-text">
              <p>Current assessments indicate a heightened probability of supply disruption in the <span className="text-red">Gulf of Aden corridor</span>. Kinetic activity reported at 0642Z correlates with previous intelligence cycles. Our predictive modeling suggests a <span className="text-amber">14% increase in spot prices</span> within the next 48-hour trading window if terminal access remains contested.</p>
              <br/>
              <p>Strategic Petroleum Reserve (SPR) levels are currently below the optimal tactical cushion. Diverting alternate vessels via the Cape of Good Hope is recommended for all non-escorted commercial assets.</p>
            </div>
            
            <div className="report-widgets">
              <div className="widget panel">
                <div className="widget-icon text-teal">@</div>
                <div className="widget-info">
                  <div className="widget-label">SIGNAL STRENGTH</div>
                  <div className="widget-value text-main">NOMINAL (0.88)</div>
                </div>
              </div>
              
              <div className="widget panel">
                <div className="widget-icon text-amber">!</div>
                <div className="widget-info">
                  <div className="widget-label">CONTINGENCY STATE</div>
                  <div className="widget-value text-amber">YELLOW-04</div>
                </div>
              </div>
            </div>
          </div>
          
          <div className="report-footer-actions">
            <button className="btn-amber-full"><span className="icon">📄</span> GENERATE EXECUTIVE REPORT</button>
          </div>
        </div>
      </div>
    </div>
  );
};

export default Dashboard;
